Create TABLE alumni_table(
    alumniID int NOT NULL,
    fName char(10) NOT NULL,
    lName char(10) NOT NULL,
    email nchar(20) NOT NULL,
    phone char(12) NOT NULL,
    DOB date,
    Gender char(1) NOT NULL,
    Ethnicity tinyint(1) NOT NULL,
    website char,
    linkedin_link char,
    twitter_link char,
    facebook_link char,
    instagram_link char,
    guestSpeakerYN char(1)NOT NULL,
    newsLetterYN char(1)NOT NULL,
    imageThumb char,
    imageNormal char,
    alumni_desc char,
    deceasedYN char(1)NOT NULL,
    deceasedDT date,
    deceasedNotes char,

    PRIMARY KEY (alumniID)
);